version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '3001:3001'
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database

  socket:
    build: ./socket
    ports:
      - '4001:4001'
    depends_on:
      - backend

volumes:
  db-data:
